### PR TITLE
Bad button project

### PR DESCRIPTION
**Pull request by ansharora28**
Css based button that has only one job,not doing it!

### CODE REVIEW

**Comment by ansharora28** [comment]
closes #1

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
@ansharora28 Kindly add some screenshots of your project in the Readme.md file and also share a demo video of your project. This will help me review your project faster.

**Comment by ansharora28** [comment]
@LiQuiD-404 

Updated, Please take a look!

**Review by LiQuiD-404 — CHANGES_REQUESTED** [review]
@ansharora28 Add the screenshots and the demo video in the PR chat.

**Pull request closed without merging**
